version: '3.8'

services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
    ports:
      - "8000:8000"
    depends_on:
      - client
      - mongo
      - server
      - redis
    networks:
      - default  # Attaches to the default network

  mongo:
    env_file:
      - ./.env.dev
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data.dev/db:/data/db
    command: --quiet
    ports:
      - "${DB_PORT}:27017"
    networks:
      - default  # Attaches to the default network

  redis:
    container_name: cache-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data.dev/cache:/data
    command: --save 60 1
    networks:
      - default  # Attaches to the default network

  server:
    restart: unless-stopped
    external_links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
    build:
      context: ./server
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    env_file:
      - ./.env.dev
    volumes:
      - ./server/src:/server/src
      - ./.data.dev/playbooks:/playbooks
      - ./.data.dev/config:/ansible-config
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - default  # Attaches to the default network

  client:
    restart: unless-stopped
    environment:
      DEBUG: http-proxy-middleware*
    depends_on:
      - server
    build:
      context: ./client
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    volumes:
      - ./client/src:/client/src
      - ./client/config:/client/config
      - ./client/public:/client/public
    networks:
      - default  # Attaches to the default network

  discovery:
    build:
      context: ./discovery
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
      - server
      - client
    networks:
      - default  # Attaches to the default network for communication with other services
      - discovery-network  # Attaches to the custom network for discovery tasks

networks:
  discovery-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_multicast: "true"
