services:
  proxy:
    restart: unless-stopped
    build:
      context: ./proxy
    ports:
      - "8000:8000"
    depends_on:
      - client
      - mongo
      - server
      - redis
      - prometheus
    labels:
      wud.display.name: "SSM - Proxy"
      wud.watch.digest: false
  prometheus:
    build:
      context: ./prometheus  # Directory containing Dockerfile and prometheus.yml
    container_name: prometheus-ssm
    restart: unless-stopped
    env_file:
      - ./.env.dev
    volumes:
      - ./.data.dev/prometheus:/prometheus
    ports:
      - "9090:9090"  # Prometheus UI accessible on this port
    labels:
      wud.display.name: "SSM - Prometheus"
  mongo:
    env_file:
      - ./.env.dev
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - ./.data.dev/db:/data/db
    command: --quiet
    ports:
      - "${DB_PORT}:27017"
    labels:
      wud.display.name: "SSM - MongoDB"
      wud.watch.digest: false
  redis:
    container_name: cache-ssm
    image: redis
    restart: unless-stopped
    volumes:
      - ./.data.dev/cache:/data
    command: --save 60 1
    labels:
      wud.display.name: "SSM - Redis"
      wud.watch.digest: false
  server:
    restart: unless-stopped
    healthcheck:
      test: curl --fail http://localhost:3000/ping || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s
    external_links:
      - mongo
      - redis
      - prometheus
    depends_on:
      - mongo
      - redis
      - prometheus
    build:
      context: ./server
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    env_file:
      - ./.env.dev
    volumes:
      - ./server/src:/opt/squirrelserversmanager/server/src
      - ./.data.dev:/data
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    ports:
      - "3000:3000"  # Main API port
    labels:
      wud.display.name: "SSM - Server"
      wud.watch.digest: false
  client:
    restart: unless-stopped
    environment:
      DEBUG: http-proxy-middleware*
    depends_on:
      - server
    build:
      context: ./client
      additional_contexts:
        - shared-lib=./shared-lib
      target: dev
    volumes:
      - ./client/src:/opt/squirrelserversmanager/client/src
      - ./client/config:/opt/squirrelserversmanager/client/config
      - ./client/public:/opt/squirrelserversmanager/client/public
    labels:
      wud.display.name: "SSM - Client"
      wud.watch.digest: false