export enum Checks {
  SSH_CONNECT = 'SSH_CONNECT',
  SSH_DOCKER_CONNECT = 'SSH_DOCKER_CONNECT',
  DOCKER_SOCKET = 'DOCKER_SOCKET',
  DISK_SPACE = 'DISK_SPACE',
  CPU_MEMORY_INFO= 'CPU_MEMORY_INFO'
}
