---
#  ,;;:;,
#   ;;;;;
#  ,:;;:;    ,'=.
#  ;:;:;' .=" ,'_\
#  ':;:;,/  ,__:=@
#   ';;:;  =./)_
#     `"=\_  )_"`
#          ``'"`
# Playbook Name: Check Device connectivity before adding
# Description: This playbook checks that the device is reachable.
# Module: SSM-CORE
# Tags: installation, agent, ping, connectivity

- name: Check Device connectivity before adding
  hosts: all
  tasks:
    - name: Test Connection
      ping:
      timeout: 600
- name: Test Sudo Working
  hosts: all
  tasks:
    - become: true
      command: id -u
      register: id_output
    - assert:
        that: id_output.stdout == '0'
- name: Task completion summary
  hosts: all
  tasks:
    - debug:
        msg: "Become completed with {{ id_output.stdout }}"
