enum Events {
  AUTOMATION_FAILED = 'AUTOMATION_FAILED',
  DOCKER_WATCH_FAILED = 'DOCKER_WATCH_FAILED',
  DOCKER_STAT_FAILED = 'DOCKER_STAT_FAILED',
  APP_STARTED = 'APP_STARTED',
  UPDATED_CONTAINERS = 'UPDATED_CONTAINERS',
  UPDATED_NOTIFICATIONS = 'UPDATED_NOTIFICATIONS',
}

export default Events;
