enum Events {
  AUTOMATION_FAILED = 'AUTOMATION_FAILED',
  DOCKER_WATCH_FAILED = 'DOCKER_WATCH_FAILED',
  DOCKER_STAT_FAILED = 'DOCKER_STAT_FAILED',
  APP_STARTED = 'APP_STARTED',
  UPDATED_CONTAINERS = 'UPDATED_CONTAINERS',
  UPDATED_NOTIFICATIONS = 'UPDATED_NOTIFICATIONS',
  ALERT = 'ALERT',
  VOLUME_BACKUP = 'VOLUME_BACKUP',
  DIAGNOSTIC_CHECK = 'DIAGNOSTIC_CHECK',
  DEVICE_CREATED = 'DEVICE_CREATED',
  DEVICE_CONFIGURATION_UPDATED = 'DEVICE_CONFIGURATION_UPDATED',
  USER_CREATED = 'USER_CREATED',
  UPDATED_SCHEME_VERSION = 'UPDATED_SCHEME_VERSION',
  REGISTER_PLAYBOOK_REGISTERS = 'REGISTER_PLAYBOOK_REGISTERS',
  TELEMETRY_EVENT = 'TELEMETRY_EVENT',
  SERVER_RESTART_REQUEST = 'SERVER_RESTART_REQUEST',
}

export default Events;
