---
# tasks/debian.yml

- name: Perform a dist-upgrade.
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Check if a reboot is required.
  ansible.builtin.stat:
    path: /var/run/reboot-required
    get_checksum: no
  register: reboot_required_file

- name: Reboot the server if required.
  ansible.builtin.reboot:
  when: reboot_required_file.stat.exists

- name: Remove dependencies that are no longer required.
  ansible.builtin.package:
    autoremove: true
