name: '[RELEASE] Post on Discord on new release'

on:
  workflow_run:
    workflows: ["[RELEASE] Publish Containers to Ghcr.io"]
    types: [completed]
    branches: [master]

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          
      - name: Get latest tag
        id: latestTag
        run: |
          echo "TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          
      - name: Discord notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          username: Release Bot
          description: |
            **New version released!** 🚀
            Version: ${{ steps.latestTag.outputs.TAG }}
            
            Check out the latest release: https://github.com/${{ github.repository }}/releases/latest
          footer: "Squirrel Servers Manager"
          webhookUrl: ${{ secrets.WEBHOOK_URL }}